In [18]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [19]:
df = pd.read_csv('/content/Iris.csv')
display(df.head())

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [20]:
df.shape

(150, 6)

In [31]:
#Pytorch with Tensor

In [32]:
import torch
import numpy as np

In [33]:
torch.__version__

'2.9.0+cpu'

In [34]:
# chuyển đổi mảng numpy sang tensor pytorh

arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)
print(type[arr])

[1 2 3 4 5]
int64
type[array([1, 2, 3, 4, 5])]


In [35]:
x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [36]:
print(x.dtype)

torch.int64


In [37]:
print(x.type())

torch.LongTensor


In [38]:
arr2 = np.arange(0.,12.).reshape(4,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.]])

In [39]:

x = torch.from_numpy(arr)
print(x)

tensor([1, 2, 3, 4, 5])


In [40]:
arr[0] = 99
print(x)

tensor([99,  2,  3,  4,  5])


In [41]:
arr = np.arange(0,5)
x = torch.tensor(arr)
print(x)

tensor([0, 1, 2, 3, 4])


In [42]:
arr[0] = 99
print(x)

tensor([0, 1, 2, 3, 4])


In [43]:
#BTVN 04: Giải thích 2 trường hợp trên
#BTVN 05: Tạo tensor với empty , zeros , ones , random , Reshape với view và view as

In [ ]:
# BTVN

# Cho y = 5x^5 + 6x^3 -3x + 1
# Cho biết độ dốc của đa thức trên ở điểm nào

#BTVN 2:
# Tạo một tensor ban đầu có giá trị là 2. Định nghĩa hàm số và tính ra gradient
# y = x^3 + 2x^2 + 5x + 1
# Hãy tính dy/dx tại giá trị của x
#Dùng phương pháp Gradient Descent với Learning rate alpha = 0.1 để cập nhật giá trị x trong vòng 10 vòng lặp

#BTVN 3:
# Tạo một tập dữ liệu giả lập với x là số giờ học ( Ngẫu nhiên từ 1 - 10) và y là số điểm
# trong cong thức y = 3x + 5 + noise . Với noise là một giá trị ngẫu nhiên nhỏ
# 1. Khởi tạo tham số w và b ngẫu nhiên với requires_grad = True
# 2. Tính MSE
# 3. Tính Gradient
# 4. Cập nhật tham số w và b bằng Gradient Descent với Learning rate alpha = 0.1
# 5. Lập lại quá trình trên trong 100 vòng lặp để xem sự hội tụ của mô hình


BTVN 1

In [49]:
import torch
x = torch.tensor(2.0,requires_grad=True)
y = 5*x**5 + 6*x**3 -3*x + 1
print(y)


tensor(203., grad_fn=<AddBackward0>)


BTVN 2

In [51]:
#Tạo một tensor ban đầu có giá trị là 2
# Learning rate và số vòng lặp
# Định nghĩa hàm
# Tính gradient
# Lưu kết quả
# Cập nhật x
# Reset gradient
# Tạo bảng kết quả
x = torch.tensor(2.0, requires_grad=True)
alpha = 0.1
epochs = 10
result = []
for i in range(epochs):
    y = x**3 + 2*x**2 + 5*x + 1
    y.backward()
    result.append([i+1, x.item(), y.item(), x.grad.item()])
    with torch.no_grad():
        x -= alpha * x.grad
    x.grad.zero_()

df = pd.DataFrame(result, columns=["Iteration", "x", "y", "dy/dx"])
print(df)

   Iteration           x             y         dy/dx
0          1    2.000000  2.700000e+01     25.000000
1          2   -0.500000 -1.125000e+00      3.750000
2          3   -0.875000 -2.513672e+00      3.796875
3          4   -1.254688 -4.100136e+00      4.703972
4          5   -1.725085 -6.807298e+00      7.027413
5          6   -2.427826 -1.366088e+01     12.971715
6          7   -3.724998 -4.156038e+01     31.726830
7          8   -6.897680 -2.665102e+02    120.143257
8          9  -18.912006 -6.142375e+03   1002.343933
9         10 -119.146408 -1.663590e+06  42116.011719


BTVN 3

In [58]:
# Tạo dữ liệu
# Khởi tạo tham số
# Dự đoán
# MSE Loss
# Tính gradient
# Lưu kết quả
# Cập nhật Gradient Descent
# Reset gradient
np.random.seed(0)
x = torch.tensor(np.random.uniform(1, 10, 20), dtype=torch.float32)
noise = torch.randn(20) * 0.5
y = 3 * x + 5 + noise

w = torch.randn(1, requires_grad=True)
b = torch.randn(1, requires_grad=True)

alpha = 0.1
epochs = 100
log = []

for i in range(epochs):
    y_pred = w * x + b
    loss = ((y_pred - y) ** 2).mean()
    loss.backward()
    log.append([i+1, loss.item(), w.item(), b.item()])
    with torch.no_grad():
        w -= alpha * w.grad
        b -= alpha * b.grad
    w.grad.zero_()
    b.grad.zero_()

df = pd.DataFrame(log, columns=["Iteration", "Loss", "w", "b"])
print(df.tail())


    Iteration  Loss   w   b
95         96   NaN NaN NaN
96         97   NaN NaN NaN
97         98   NaN NaN NaN
98         99   NaN NaN NaN
99        100   NaN NaN NaN


BTVN 4

In [ ]:
arr = np.array([1,2,3,4,5])
x = torch.from_numpy(arr)

arr[0] = 99
print(x)

Với trường hợp này:
+ x chia sẻ chung bộ nhớ với arr
+ Khi bạn thay đổi arr, thì x thay đổi theo
+ Không copy dữ liệu chỉ tạo view và numpy array

In [ ]:
arr = np.arange(0,5)
x = torch.tensor(arr)

arr[0] = 99
print(x)

Với trường hợp này:
+ x không thay đổi
+ x và arr không chung bộ nhớ
+ Copy dữ liệu sang vùng mới

BTVN 5


In [61]:
#Tạo tensor
x = torch.empty(2, 3)
print(x)

tensor([[3.8511e-23, 0.0000e+00, 4.8982e-23],
        [0.0000e+00, 1.1210e-43, 0.0000e+00]])


In [62]:
x = torch.zeros(2, 3)
print(x)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [63]:
x = torch.ones(2, 3)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [64]:
x = torch.rand(2, 3)
print(x)

tensor([[0.5594, 0.9790, 0.6112],
        [0.0286, 0.0950, 0.4901]])


In [65]:
#Reshape tensor
x = torch.arange(0, 12)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


View

In [66]:
y = x.view(4, 3)
print(y)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])


Viewas

In [ ]:
z = torch.zeros(4, 3)
y = x.view_as(z)
print(y)