# DEEP LEARNING 

## Tuần 2 : NUMPY , PANDAS , MATPLOTLIB

# NUMPY


In [1]:
# NUMPY là thư viện kiểu list vì
# + Numpy nhanh
# + có nhiều hàm tích hợp dễ sử dụng cho AI

# Để sử dụng numpy thì : piip install numpy
import numpy as np 

In [2]:
# thử tạo 1 list
python_list = [1,2,3]
# chuyển đổi danh sách trên thành numpy list

numpy_list = np.array(python_list)

type(numpy_list)

numpy.ndarray

In [ ]:
# list trong python có thể  hỗ trợ nhiều loại dữ liệu trong list

my_list = [1,"chào",True, 2.0]

In [5]:
my_list = [1,2,3,4.5]
np_list = np.array(my_list)
np_list

array([1. , 2. , 3. , 4.5])

In [6]:
# Chuyển đổi kiểu dữ liệu 
np_list_int = np_list.astype(int)
np_list_int

array([1, 2, 3, 4])

In [8]:
# acessing và indexing

x = np.array([1,2,3,4,5,6,7,8]) # x = np.array(range(1,9))

In [9]:
# lấy số 4 
x[3]

np.int64(4)

In [11]:
# lấy nhiều hơn 1 phần tử 
# công thức [start:and:step]
# lấy từ vị trí 1 đến vị trí 3
x[0:3]

array([1, 2, 3])

In [22]:
# lấy tử 3 đến 8 theo 3 cách
x[2:8]
x[2:]
x[2:8:1]

array([3, 4, 5, 6, 7, 8])

In [23]:
# đặt danh sách các index muốn truy cập
x[[2,4]]

array([3, 5])

In [25]:
data = [[1,2], [3,4], [5,6]]
np_list = np.array(data)
np_list

array([[1, 2],
       [3, 4],
       [5, 6]])

In [27]:
# lấy số 2 
np_list[0:1]

array([[1, 2]])

In [32]:
#lấy số 6
np_list[2,1]

np.int64(6)

In [34]:
# lấy [3,4] , [5,6]
# np_list[1:3]
# Cho tôi cách số 2
np_list[1:, :]

array([[3, 4],
       [5, 6]])

In [36]:
np_list[-2:]

array([[3, 4],
       [5, 6]])

In [46]:
# lấy 1 và 5 

x[::2,0]

array([1, 5])

In [52]:
x = [
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
]

np_list = np.array(x)

np_list

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [63]:
# lấy 2 6 10 14 
np_list[:,1]
# lấy 7 và 11 ( sử dụng bước nhảy )
np_list[1:3,2]
np_list[[0, 1, 2], [3, 2, 1]]

np

<module 'numpy' from 'c:\\Users\\ADMIN\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

In [ ]:
np_list[3,::-1]


array([16, 15, 14, 13])

In [ ]:
# BTVN 1 
# cho ma trận bằng [[99,99,99],
#                   [99,99,99],
#                   [99,99,99]]

# hãy tưởng tượng ô 99 trống
# giả sử 1 là x 
# giả sử 0 là o 
# lấy đầu vào từ phía X và phái O luân phiên 
# Nếu đầu vào từ phía x là (0,0)
# thì ma trận sẽ trở thành 
#                  [[x,99,99],
#                   [99,99,99],
#                   [99,99,99]]

# Nếu đầu vào từ phía o là (0,0)
# Thông báo họ nhập lại 
# nếu không thì điền vào ma trận

# Thử thách : Nếu người đầu tiên có 3 phần tử liên tục thì dừng trò chơi

import numpy as np

def check_win(board, player):
    # Check rows
    for i in range(3):
        if np.all(board[i, :] == player):
            return True
    # Check columns
    for i in range(3):
        if np.all(board[:, i] == player):
            return True
    # Check diagonals
    if np.all(np.diag(board) == player):
        return True
    if np.all(np.diag(np.fliplr(board)) == player):
        return True
    return False

# Initialize board
board = np.full((3, 3), 99)
current_player = 1  # 1 for X, 0 for O

while True:
    print("Bảng hiện tại:")
    print(board)
    print(f"Player {'X' if current_player == 1 else 'O'}'s turn")
    
    # Get input
    try:
        row, col = map(int, input("Nhập số hàng và số cột (0-2, cách nhau bằng dấu cách):").split())
    except ValueError:
        print("Nhập liệu không hợp lệ. Vui lòng nhập hai số cách nhau bằng dấu cách.")
        continue
    
    # Check bounds
    if not (0 <= row < 3 and 0 <= col < 3):
        print("Vị trí nằm ngoài phạm vi. Thử lại.")
        continue
    
    # Special rule for O
    if current_player == 0 and (row, col) == (0, 0):
        print("O không thể chơi tại (0,0). Thử lại.")
        continue
    
    # Check if position is empty
    if board[row, col] != 99:
        print("Vị trí đã có người đánh. Vui lòng thử lại.")
        continue
    
    # Place the mark
    board[row, col] = current_player
    
    # Check for win
    if check_win(board, current_player):
        print("Bảng hiện tại:")
        print(board)
        print(f"Player {'X' if current_player == 1 else 'O'} wins!")
        break
    
    # Switch player
    current_player = 1 - current_player

Bảng hiện tại:
[[99 99 99]
 [99 99 99]
 [99 99 99]]
Player X's turn
Nhập liệu không hợp lệ. Vui lòng nhập hai số cách nhau bằng dấu cách.
Bảng hiện tại:
[[99 99 99]
 [99 99 99]
 [99 99 99]]
Player X's turn
Bảng hiện tại:
[[99 99 99]
 [99  1 99]
 [99 99 99]]
Player O's turn
Bảng hiện tại:
[[99  0 99]
 [99  1 99]
 [99 99 99]]
Player X's turn
Vị trí nằm ngoài phạm vi. Thử lại.
Bảng hiện tại:
[[99  0 99]
 [99  1 99]
 [99 99 99]]
Player X's turn
Bảng hiện tại:
[[99  0  1]
 [99  1 99]
 [99 99 99]]
Player O's turn
O không thể chơi tại (0,0). Thử lại.
Bảng hiện tại:
[[99  0  1]
 [99  1 99]
 [99 99 99]]
Player O's turn
Bảng hiện tại:
[[99  0  1]
 [99  1 99]
 [ 0 99 99]]
Player X's turn
Nhập liệu không hợp lệ. Vui lòng nhập hai số cách nhau bằng dấu cách.
Bảng hiện tại:
[[99  0  1]
 [99  1 99]
 [ 0 99 99]]
Player X's turn
Nhập liệu không hợp lệ. Vui lòng nhập hai số cách nhau bằng dấu cách.
Bảng hiện tại:
[[99  0  1]
 [99  1 99]
 [ 0 99 99]]
Player X's turn
Nhập liệu không hợp lệ. Vui lòng nhập 

In [1]:
# BTVN 2 

# cho y = [
#          [1,2,3],
#          [4,5,6],
#          [7,8,9]
#          ]
# lấy 4,5,6
# lấy 2,5
# lấy 3,4
# lấy 9,6,3

import numpy as np

y = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

print("Lấy 4,5,6:")
print(y[1])

print("Lấy 2,5:")
print(y[:,1])

print("Lấy 3,4")
print(y[0,2], y[1,0])

print("Lấy 9,6,3:")
print(y[::-1,2])

Lấy 4,5,6:
[4 5 6]
Lấy 2,5:
[2 5 8]
Lấy 3,4
3 4
Lấy 9,6,3:
[9 6 3]


In [ ]:
# BTVN 3
# Cho x = [1,2,3,4,5,6,7,8,9,10]
# 1. xuất ra các giá trị chẵn sử dụng if
# 2. xuất ra các giá trị chẵn sử dụng list comprehension

In [73]:
np_x = np.array(range(10))
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [74]:
np_x[np_x % 2 == 0]

array([0, 2, 4, 6, 8])

In [75]:
np_x % 2 == 0

array([ True, False,  True, False,  True, False,  True, False,  True,
       False])

In [76]:
idx = [ True, False,  True, False,  True, False,  True, False,  True,
       False]

np_x[idx]

array([0, 2, 4, 6, 8])

In [ ]:
np_x

In [80]:
cond1 = np_x % 2 != 0
cond2 = np_x < 5
cond3 = np_x > 0

np_x[cond1 & cond2 | cond3]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [2]:
#BTVN 4 
# tạo 1 mảng numpy với kích thước 150x5 , Giả sử mảng này chưa 150 mẫu
# dữ liệu của sinh viên bao gồm chiều cao, cân nặng, tuổi , lương, điểm trung bình
# tách mảng x thành 2 dựa trên 4 cột đầu tiên thành 1 biến có tên là x và cột cuối cùng thành y

# tách x thành x_train và x_test trong đó x_train chưa 70% dữ liệu
# và tách y thành y_train và y_test , trong đó y_train chứa 70%
# dữ liệu

# Tạo 10 tập dữ liệu x_train không chồng chéo nhau 

import numpy as np

np.random.seed(42)  

data = np.random.rand(150, 5)

data[:, 0] = data[:, 0] * 50 + 150  # Chiều cao
data[:, 1] = data[:, 1] * 60 + 40   # Cân nặng
data[:, 2] = data[:, 2] * 7 + 18    # Tuổi
data[:, 3] = data[:, 3] * 100000    # Lương
data[:, 4] = data[:, 4] * 4         # GPA

print("Kích thước dữ liệu:", data.shape)

X = data[:, :4]
y = data[:, 4]

print("Kích thước X:", X.shape)
print("Kích thước y:", y.shape)

train_size = int(0.7 * 150)
X_train = X[:train_size]
X_test = X[train_size:]
y_train = y[:train_size]
y_test = y[train_size:]

print("Kích thước X_train:", X_train.shape)
print("Kích thước X_test:", X_test.shape)
print("Kích thước y_train:", y_train.shape)
print("Kích thước y_test:", y_test.shape)

indices = np.arange(len(X_train))
np.random.shuffle(indices)

splits = np.array_split(indices, 10)

x_trains = [X_train[split] for split in splits]
y_trains = [y_train[split] for split in splits]

print("Số lượng tập x_train:", len(x_trains))
for i, xt in enumerate(x_trains):
    print(f"Kích thước x_train[{i}]:", xt.shape)

Kích thước dữ liệu: (150, 5)
Kích thước X: (150, 4)
Kích thước y: (150,)
Kích thước X_train: (105, 4)
Kích thước X_test: (45, 4)
Kích thước y_train: (105,)
Kích thước y_test: (45,)
Số lượng tập x_train: 10
Kích thước x_train[0]: (11, 4)
Kích thước x_train[1]: (11, 4)
Kích thước x_train[2]: (11, 4)
Kích thước x_train[3]: (11, 4)
Kích thước x_train[4]: (11, 4)
Kích thước x_train[5]: (10, 4)
Kích thước x_train[6]: (10, 4)
Kích thước x_train[7]: (10, 4)
Kích thước x_train[8]: (10, 4)
Kích thước x_train[9]: (10, 4)
